blog_old/urls.py
from django.urls import path, register_converter

from . import views

class FourDigitYearConverter:
    regex = '[0-9]{4}'

    def to_python(self, value):
        return int(value)

    def to_url(self, value):
        return '%04d' % value


class MonthConverter:
    regex = '[0-9]{1,2}'

    def to_python(self, value):
        return int(value)

    def to_url(self, value):
        return value


class PageNumConverter:
    regex = '\d*'

    def to_python(self, value):
        return int(value) if value != '' else 1;

    def to_url(self, value):
        return value


register_converter(FourDigitYearConverter, 'yyyy')
register_converter(MonthConverter, 'mm')
register_converter(PageNumConverter, 'page')

app_name = 'blog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('index/<int:page_num>', views.IndexView.as_view(), name='index'),
    path('month/<yyyy:year>/<mm:month>/<page:page_num>', views.MonthListView.as_view(), name='month_list'),
    path('tag/<slug:tag>/<page:page_num>', views.TagListView.as_view(), name='tag_list'),
    path('search', views.SearchResultListView.as_view(), name='search_result_list'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
]

project_core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

blog/models/article.py
from django.db import models


class Article(models.Model):
    STATUS_MAP = {
        'DRAFT': 0,
        'PUBLIC': 1,
    }

    title = models.CharField(max_length=100)
    body = models.TextField()
    status = models.SmallIntegerField(
        choices=[(v, k) for k, v in STATUS_MAP.items()],
        default=0,
    )
    tags = models.ManyToManyField('ArticleTag', blank=True)
    created_dt = models.DateTimeField(auto_now_add=True)
    updated_dt = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def to_dict(self):
        tags = []
        for tag in self.tags.values():
            tags.append(tag['name'])

        return {
            'title': self.title,
            'body': self.body,
            'status': self.status,
            'tags': tags,
            'created_at': self.created_dt,
            'updated_at': self.updated_dt,
        }

blog_old/models/article.py
from django.db import models


class Article(models.Model):
    STATUS_MAP = {
        'DRAFT': 0,
        'PUBLIC': 1,
    }

    title = models.CharField(max_length=100)
    body = models.TextField()
    status = models.SmallIntegerField(
        choices=[(v, k) for k, v in STATUS_MAP.items()],
        default=0,
    )
    tags = models.ManyToManyField('ArticleTag', blank=True)
    created_dt = models.DateTimeField(auto_now_add=True)
    updated_dt = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

blog_old/models/article_tag.py
from django.db import models


class ArticleTag(models.Model):
    def __str__(self):
        return self.name

    name = models.SlugField(max_length=30, db_index=True)
    created_dt = models.DateTimeField(auto_now_add=True)
    updated_dt = models.DateTimeField(auto_now=True)

blog/views.py
import json
from django.core import serializers
from django.http import JsonResponse, HttpResponse
from django.views import generic

from .models.article import Article


LMT = 3

class BaseView(generic.View):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # URLパラメータをすべてレスポンスのコンテキスト内に詰める
        context.update(self.kwargs)
        # TODO 年月ごとの記事数のリストの生成
        # TODO タグとそれに紐づく記事数のリストの生成
        return context


class IndexView(BaseView, generic.ListView):
    template_name = 'blog/index.html'

    def get_queryset(self):
        page_num = self.kwargs.get('page_num', 1)
        start = LMT * (page_num - 1)
        return Article.objects.filter(status=Article.STATUS_MAP['PUBLIC']).order_by('-created_dt')[start:(start + LMT)]


def top(req):
    page_num = int(req.GET.get('page_num', 1))
    start = LMT * (page_num - 1)
    articles = Article.objects.filter(status=Article.STATUS_MAP['PUBLIC']).order_by('-created_dt')[start:(start + LMT)]
    return _create_json_response(list(map(lambda a: a.to_dict(), articles)))


class MonthListView(BaseView, generic.ListView):
    template_name = 'blog/month_list.html'

    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        page_num = self.kwargs.get('page_num', 1)
        start = LMT * (page_num - 1)
        return Article.objects.filter(status=Article.STATUS_MAP['PUBLIC']).order_by('-created_dt')[start:(start + LMT)]


class TagListView(BaseView, generic.ListView):
    template_name = 'blog/tag_list.html'

    def get_queryset(self):
        tag = self.kwargs.get('tag')
        page_num = self.kwargs.get('page_num', 1)
        start = LMT * (page_num - 1)
        return Article.objects.filter(status=Article.STATUS_MAP['PUBLIC']).order_by('-created_dt')[start:(start + LMT)]


class SearchResultListView(BaseView, generic.ListView):
    template_name = 'blog/search_result_list.html'

    params = {}

    def __get_params(self):
        if not self.params:
            query_params = self.request.GET
            self.params = {
                'word': query_params.get('w'),
                'page_num': query_params.get('p', 1),
            }

        return self.params

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(self.__get_params())
        return context

    def get_queryset(self):
        word, page_num = self.__get_params().values()
        print("word: {}".format(word))
        print("page_num: {}".format(page_num))
        return Article.objects.filter(status=Article.STATUS_MAP['PUBLIC']).order_by('-created_dt')[:3]


class DetailView(BaseView, generic.DetailView):
    model = Article
    queryset = Article.objects.filter(status=Article.STATUS_MAP['PUBLIC'])

def _create_json_response(content):
    return JsonResponse(content, safe=False, json_dumps_params={'ensure_ascii': False})

blog_old/views.py
from django.views import generic
from .models.article import Article


LMT = 3

class BaseView(generic.View):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # URLパラメータをすべてレスポンスのコンテキスト内に詰める
        context.update(self.kwargs)
        # 年月ごとの記事数のリスト
        # タグとそれに紐づく記事数のリスト
        return context


class IndexView(BaseView, generic.ListView):
    template_name = 'blog/index.html'

    def get_queryset(self):
        page_num = self.kwargs.get('page_num', 1)
        start = LMT * (page_num - 1)
        return Article.objects.filter(status=Article.STATUS_MAP['PUBLIC']).order_by('-created_dt')[start:(start + LMT)]


class MonthListView(BaseView, generic.ListView):
    template_name = 'blog/month_list.html'

    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        page_num = self.kwargs.get('page_num', 1)
        start = LMT * (page_num - 1)
        return Article.objects.filter(status=Article.STATUS_MAP['PUBLIC']).order_by('-created_dt')[start:(start + LMT)]


class TagListView(BaseView, generic.ListView):
    template_name = 'blog/tag_list.html'

    def get_queryset(self):
        tag = self.kwargs.get('tag')
        page_num = self.kwargs.get('page_num', 1)
        start = LMT * (page_num - 1)
        return Article.objects.filter(status=Article.STATUS_MAP['PUBLIC']).order_by('-created_dt')[start:(start + LMT)]


class SearchResultListView(BaseView, generic.ListView):
    template_name = 'blog/search_result_list.html'

    params = {}

    def __get_params(self):
        if not self.params:
            query_params = self.request.GET
            self.params = {
                'word': query_params.get('w'),
                'page_num': query_params.get('p', 1),
            }

        return self.params

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(self.__get_params())
        return context

    def get_queryset(self):
        word, page_num = self.__get_params().values()
        print("word: {}".format(word))
        print("page_num: {}".format(page_num))
        return Article.objects.filter(status=Article.STATUS_MAP['PUBLIC']).order_by('-created_dt')[:3]


class DetailView(BaseView, generic.DetailView):
    model = Article
    queryset = Article.objects.filter(status=Article.STATUS_MAP['PUBLIC'])

blog/templates/blog/base_react.html
<!DOCTYPE html>
<html>
<head>
<title>tnbe21 blog</title>
<style>
main {
  float: left;
  padding: 0 10px;
  width: 80%;
}
aside {
  float: left;
  padding: 0 10px;
}
h1 a {
  color: #000000;
  text-decoration: none;
}
{% block uniq_css %}
{% endblock %}
</style>
</head>
<body>
<header>
  <h1><a href="{% url 'blog:index' %}">tnbe21 blog</a></h1>
</header>
<main>
{% block main %}
{% endblock %}
</main>
<aside>
  <div id="search">
    <h3>SEARCH</h3>
    <form id="search_form" action="/blog/search" method="GET">
      <input type="text" name="w">
      <input type="submit" value="GO">
    </form>
  </div>
  <nav>
    <h3>年月別</h3>
    <ul>
      <li>
        <h4>2020(折りたたみ)</h4>
        <ul>
          <li><a href="{% url 'blog:month_list' 2020 5 '' %}">2020.05(2)</a></li>
          <li>2020.04(1)</li>
          <li>2020.03(10)</li>
          <li>2020.01(4)</li>
        </ul>
      </li>
      <li>
        <h4>2019</h4>
        <ul>
          <li>2020.12(1)</li>
          <li>2020.08(2)</li>
          <li>2020.02(5)</li>
        </ul>
      </li>
    </ul>
  </nav>
  <nav>
    <h3>タグ別</h3>
    <ul>
      <li><a href="{% url 'blog:tag_list' 'DIARY' '' %}">DIARY(20)</a></li>
      <li>TECH(40)</li>
    </ul>
  </nav>
</aside>
</body>
</html>

blog/templates/blog/base_vue.html
<!DOCTYPE html>
<html>
<head>
<title>tnbe21 blog</title>
<style>
main {
  float: left;
  padding: 0 10px;
  width: 80%;
}
aside {
  float: left;
  padding: 0 10px;
}
h1 a {
  color: #000000;
  text-decoration: none;
}
{% block uniq_css %}
{% endblock %}
</style>
</head>
<body>
<header>
  <h1><a href="{% url 'blog:index' %}">tnbe21 blog</a></h1>
</header>
<main>
{% block main %}
{% endblock %}
</main>
<aside>
  <div id="search">
    <h3>SEARCH</h3>
    <form id="search_form" action="/blog/search" method="GET">
      <input type="text" name="w">
      <input type="submit" value="GO">
    </form>
  </div>
  <nav>
    <h3>年月別</h3>
    <ul>
      <li>
        <h4>2020(折りたたみ)</h4>
        <ul>
          <li><a href="{% url 'blog:month_list' 2020 5 '' %}">2020.05(2)</a></li>
          <li>2020.04(1)</li>
          <li>2020.03(10)</li>
          <li>2020.01(4)</li>
        </ul>
      </li>
      <li>
        <h4>2019</h4>
        <ul>
          <li>2020.12(1)</li>
          <li>2020.08(2)</li>
          <li>2020.02(5)</li>
        </ul>
      </li>
    </ul>
  </nav>
  <nav>
    <h3>タグ別</h3>
    <ul>
      <li><a href="{% url 'blog:tag_list' 'DIARY' '' %}">DIARY(20)</a></li>
      <li>TECH(40)</li>
    </ul>
  </nav>
</aside>
</body>
</html>

blog/templates/blog/detail.html
{% if article %}
<h2>{{ article.title }}</h2>
<p>{{ article.body }}</p>
{% else %}
<p>記事が見つかりません</p>
{% endif %}

blog/templates/blog/index.html
{% extends "blog/base.html" %}

{% block main %}
{% if article_list %}
<ul>
{% for a in article_list %}
<li><a href="{% url 'blog:detail' a.id %}">{{ a.title }}</a></li>
{% endfor %}
</ul>
{% else %}
<p>最新の記事が見つかりません</p>
{% endif %}
{% endblock %}

blog_old/templates/blog/article_detail.html
{% extends "blog/base.html" %}

{% block uniq_css %}
#additional_info {
  text-align: right;
  padding-right: 5px;
}
{% endblock %}

{% block main %}
{% if article %}
<h2>{{ article.title }}</h2>
<p>{{ article.body|safe }}</p>
<hr>
<p id="additional_info">
<i>written in: {{ article.created_dt }}</i>
<p>
{% else %}
<p>記事が見つかりません</p>
{% endif %}
{% endblock %}

blog_old/templates/blog/base.html
<!DOCTYPE html>
<html>
<head>
<title>tnbe21 blog</title>
<style>
main {
  float: left;
  padding: 0 10px;
  width: 80%;
}
aside {
  float: left;
  padding: 0 10px;
}
h1 a {
  color: #000000;
  text-decoration: none;
}
{% block uniq_css %}
{% endblock %}
</style>
</head>
<body>
<header>
  <h1><a href="{% url 'blog:index' %}">tnbe21 blog</a></h1>
</header>
<main>
{% block main %}
{% endblock %}
</main>
<aside>
  <div id="search">
    <h3>SEARCH</h3>
    <form id="search_form" action="/blog/search" method="GET">
      <input type="text" name="w">
      <input type="submit" value="GO">
    </form>
  </div>
  <nav>
    <h3>年月別</h3>
    <ul>
      <li>
        <h4>2020(折りたたみ)</h4>
        <ul>
          <li><a href="{% url 'blog:month_list' 2020 5 '' %}">2020.05(2)</a></li>
          <li>2020.04(1)</li>
          <li>2020.03(10)</li>
          <li>2020.01(4)</li>
        </ul>
      </li>
      <li>
        <h4>2019</h4>
        <ul>
          <li>2020.12(1)</li>
          <li>2020.08(2)</li>
          <li>2020.02(5)</li>
        </ul>
      </li>
    </ul>
  </nav>
  <nav>
    <h3>タグ別</h3>
    <ul>
      <li><a href="{% url 'blog:tag_list' 'DIARY' '' %}">DIARY(20)</a></li>
      <li>TECH(40)</li>
    </ul>
  </nav>
</aside>
</body>
</html>

blog_old/templates/blog/index.html
{% extends "blog/base.html" %}

{% block main %}
{% if article_list %}
<ul>
{% for a in article_list %}
<li><a href="{% url 'blog:detail' a.id %}">{{ a.title }}</a></li>
{% endfor %}
</ul>
{% else %}
<p>記事が見つかりません</p>
{% endif %}
{% endblock %}

blog_old/templates/blog/month_list.html
{% extends "blog/base.html" %}

{% block main %}
<h2>{{ year }}年{{ month }}月の記事</h2>
{% if article_list %}
<ul>
{% for a in article_list %}
<li><a href="{% url 'blog:detail' a.id %}">{{ a.title }}</a></li>
{% endfor %}
</ul>
{% else %}
<p>記事が見つかりません</p>
{% endif %}
{% endblock %}

blog_old/templates/blog/search_result_list.html
{% extends "blog/base.html" %}

{% block main %}
<h2>検索結果: {{ word }}</h2>
{% if article_list %}
<ul>
{% for a in article_list %}
<li><a href="{% url 'blog:detail' a.id %}">{{ a.title }}</a></li>
{% endfor %}
</ul>
{% else %}
<p>記事が見つかりません</p>
{% endif %}
{% endblock %}

blog_old/templates/blog/tag_list.html
{% extends "blog/base.html" %}

{% block main %}
<h2>タグ: {{ tag }}の記事</h2>
{% if article_list %}
<ul>
{% for a in article_list %}
<li><a href="{% url 'blog:detail' a.id %}">{{ a.title }}</a></li>
{% endfor %}
</ul>
{% else %}
<p>記事が見つかりません</p>
{% endif %}
{% endblock %}